apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: coit-frontend
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - frontend.coit.io
    secretName:  frontend.app.io
  rules:
  - host: frontent-app.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: coit-frontend
            port:
              number: 80
